name: Continuous Integration and Continuous Deployment
run-name: ${{ github.actor }} submitted a CI CD Action
on:
  push:
    branches: [ "milestone6" ]

jobs:
  Explore-GitHub-Actions:
    if: contains(github.event.head_commit.message, '/run-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build Deployment Container 
        run: |-
          cd ${{ github.workspace }}/src/deployment/
          docker build -t ccb-app-deployment -f Dockerfile .
      - name: Run Deploy App
        if: contains(github.event.head_commit.message, '/run-deploy-app')
        run: |-
          docker run --rm --name ccb-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.ssh:/home/app/.ssh \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            --volume $GITHUB_WORKSPACE:/workspace \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            --env GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project-400018 \
            -e GCP_ZONE=us-east1-b \
            ccb-app-deployment sh -c "sh deploy-app.sh 2>&1"
      - name: Run download_from_dac
        if: contains(github.event.head_commit.message, '/run-download_from_dac')
        run: |-
          docker run --rm --name ccb-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/download_from_dac:/download_from_dac \
            -v ${{ github.workspace }}/src/preprocessing:/preprocessing \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project-400018 \
            -e GCP_ZONE=us-east1-b \
            -e GCS_BUCKET_NAME=baby-cry-bucket \
            -e GCS_SERVICE_ACCOUNT=deployment-630@ac215-project-400018.iam.gserviceaccount.com \
            -e GCP_REGION=us-east1 \
            ccb-app-deployment sh run-download_from_dacr.sh
      - name: Run Data Processor
        if: contains(github.event.head_commit.message, '/run-data-processor')
        run: |-
          docker run --rm --name ccb-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/download_from_dac:/download_from_dac \
            -v ${{ github.workspace }}/src/preprocessing:/preprocessing \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project-400018 \
            -e GCP_ZONE=us-east1-b \
            -e GCS_BUCKET_NAME=baby-cry-bucket \
            -e GCS_SERVICE_ACCOUNT=deployment-630@ac215-project-400018.iam.gserviceaccount.com \
            -e GCP_REGION=us-east1 \
            ccb-app-deployment sh run-data-processor.sh
#       - name: Run ML Pipeline
#         if: contains(github.event.head_commit.message, '/run-ml-pipeline')
#         run: |-
#           docker run --rm --name mushroom-app-deployment \
#             -v /var/run/docker.sock:/var/run/docker.sock \
#             -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
#             -v ${{ github.workspace }}/src/api-service:/api-service \
#             -v ${{ github.workspace }}/src/data-collector:/data-collector \
#             -v ${{ github.workspace }}/src/data-processor:/data-processor \
#             --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
#             -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
#             -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
#             -e GCP_PROJECT=ac215-project-400018 \
#             -e GCP_ZONE=us-east1-b \
#             -e GCS_BUCKET_NAME=mushroom-app-ml-workflow-demo \
#             -e GCS_SERVICE_ACCOUNT=ml-workflow@ac215-project.iam.gserviceaccount.com \
#             -e GCP_REGION=us-central1 \
#             -e GCS_PACKAGE_URI=gs://mushroom-app-trainer-code \
#             mushroom-app-deployment sh run-ml-pipeline.sh
#       - run: echo "Job's status is ${{ job.status }}."